name: dailylingo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  syncfusion_flutter_pdfviewer: ^31.1.19
  cupertino_icons: ^1.0.8
  pdfx: 2.9.2
  http: ^1.1.0
  flutter_tts: ^4.2.2
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample.pdf